use more mise

diff --git a/home/bin/install/net b/home/bin/install/net
--- a/home/bin/install/net
+++ b/home/bin/install/net
@@ -6,9 +6,9 @@ if ! apt-get update; then
     exit 1
 fi
 
-# net tools
-if ! apt-get install -y curl python3 iproute2 iw iputils-ping tcpdump wireguard; then
-    echo "apt-get install curl python3 iproute2 iw iputils-ping wireguard failed"
+# net tools (python managed by mise)
+if ! apt-get install -y curl iproute2 iw iputils-ping tcpdump wireguard; then
+    echo "apt-get install curl iproute2 iw iputils-ping tcpdump wireguard failed"
     exit 1
 fi
 
